-- Read-only metadata and aggregate inventory; no secrets or personal row values.
SET NOCOUNT ON;
SET LOCK_TIMEOUT 5000;
SELECT DB_NAME() DatabaseName,CONVERT(varchar(30),SERVERPROPERTY('ProductVersion')) ProductVersion,compatibility_level,collation_name,recovery_model_desc,is_read_committed_snapshot_on,is_auto_close_on,is_auto_shrink_on FROM sys.databases WHERE database_id=DB_ID();
SELECT HAS_PERMS_BY_NAME(DB_NAME(),'DATABASE','VIEW DEFINITION') CanViewDefinition,HAS_PERMS_BY_NAME(DB_NAME(),'DATABASE','VIEW DATABASE STATE') CanViewDatabaseState;
SELECT s.name SchemaName,t.name TableName,SUM(CASE WHEN p.index_id IN(0,1) THEN p.rows ELSE 0 END) ApproxRows FROM sys.tables t JOIN sys.schemas s ON s.schema_id=t.schema_id LEFT JOIN sys.partitions p ON p.object_id=t.object_id WHERE t.is_ms_shipped=0 GROUP BY s.name,t.name ORDER BY 1,2;
SELECT s.name SchemaName,t.name TableName,c.column_id,c.name ColumnName,ty.name TypeName,c.max_length,c.precision,c.scale,c.is_nullable,c.is_identity,c.is_computed,dc.definition DefaultDefinition FROM sys.tables t JOIN sys.schemas s ON s.schema_id=t.schema_id JOIN sys.columns c ON c.object_id=t.object_id JOIN sys.types ty ON ty.user_type_id=c.user_type_id LEFT JOIN sys.default_constraints dc ON dc.object_id=c.default_object_id WHERE t.is_ms_shipped=0 ORDER BY 1,2,3;
SELECT OBJECT_SCHEMA_NAME(i.object_id) SchemaName,OBJECT_NAME(i.object_id) TableName,i.name IndexName,i.type_desc,i.is_unique,i.is_primary_key,i.is_disabled,i.filter_definition,ic.key_ordinal,ic.is_included_column,c.name ColumnName FROM sys.indexes i JOIN sys.tables t ON t.object_id=i.object_id JOIN sys.index_columns ic ON ic.object_id=i.object_id AND ic.index_id=i.index_id JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE t.is_ms_shipped=0 ORDER BY 1,2,3,ic.index_column_id;
SELECT fk.name,OBJECT_SCHEMA_NAME(fk.parent_object_id) SchemaName,OBJECT_NAME(fk.parent_object_id) TableName,pc.name ColumnName,OBJECT_SCHEMA_NAME(fk.referenced_object_id) ReferencedSchema,OBJECT_NAME(fk.referenced_object_id) ReferencedTable,rc.name ReferencedColumn,fk.delete_referential_action_desc,fk.is_disabled,fk.is_not_trusted FROM sys.foreign_keys fk JOIN sys.foreign_key_columns fc ON fc.constraint_object_id=fk.object_id JOIN sys.columns pc ON pc.object_id=fc.parent_object_id AND pc.column_id=fc.parent_column_id JOIN sys.columns rc ON rc.object_id=fc.referenced_object_id AND rc.column_id=fc.referenced_column_id ORDER BY 2,3,1;
SELECT OBJECT_SCHEMA_NAME(parent_object_id) SchemaName,OBJECT_NAME(parent_object_id) TableName,name,definition,is_disabled,is_not_trusted FROM sys.check_constraints;
SELECT s.name SchemaName,o.name,o.type_desc FROM sys.objects o JOIN sys.schemas s ON s.schema_id=o.schema_id WHERE o.is_ms_shipped=0 AND o.type IN('V','P','FN','IF','TF','TR','SN','SO') ORDER BY 1,2;
SELECT OBJECT_SCHEMA_NAME(referencing_id) SchemaName,OBJECT_NAME(referencing_id) ObjectName,referenced_schema_name,referenced_entity_name,is_schema_bound_reference FROM sys.sql_expression_dependencies;
SELECT type_desc,permission_name,state_desc,COUNT(*) PermissionEntries FROM sys.database_permissions p JOIN sys.database_principals d ON p.grantee_principal_id=d.principal_id GROUP BY type_desc,permission_name,state_desc;
SELECT 'UsersWithoutPassword' Metric,COUNT_BIG(*) Total FROM Sec.[User] WHERE PasswordHash IS NULL OR PasswordHash='' UNION ALL SELECT 'InactiveUsers',COUNT_BIG(*) FROM Sec.[User] WHERE IsActive=0 UNION ALL SELECT 'InactiveRoleAssignments',COUNT_BIG(*) FROM Sec.UserRole ur JOIN Sec.Role r ON r.RoleId=ur.RoleId WHERE r.IsActive=0 UNION ALL SELECT 'InvalidNotificationReadState',COUNT_BIG(*) FROM Notify.UserNotification WHERE (IsRead=0 AND ReadAt IS NOT NULL) OR (IsRead=1 AND ReadAt IS NULL);
SELECT 'DuplicateTrimmedUsernames' Metric,COUNT_BIG(*) GroupsFound FROM (SELECT LTRIM(RTRIM(Username)) n FROM Sec.[User] GROUP BY LTRIM(RTRIM(Username)) HAVING COUNT(*)>1) d UNION ALL SELECT 'DuplicateNonEmptyNationalIds',COUNT_BIG(*) FROM (SELECT NationalId FROM Sec.[User] WHERE NationalId IS NOT NULL AND NationalId<>'' GROUP BY NationalId HAVING COUNT(*)>1) d UNION ALL SELECT 'DuplicateNonEmptyMobiles',COUNT_BIG(*) FROM (SELECT MobileNumber FROM Sec.[User] WHERE MobileNumber IS NOT NULL AND MobileNumber<>'' GROUP BY MobileNumber HAVING COUNT(*)>1) d;
SELECT name,type_desc,size*8/1024 SizeMB,is_percent_growth,growth FROM sys.database_files;
